# obstacle_range: 3.0
# raytrace_range: 3.5

footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
#robot_radius: 0.105

robot_base_frame: base_footprint

inflation_radius: 1.5
cost_scaling_factor: 5

map_type: costmap
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_scan, 
                    data_type: LaserScan, 
                    topic: scan, 
                    marking: true, 
                    clearing: true,
                    inf_is_valid: false}