global_costmap:
  # global_frame: map
  # robot_base_frame: base_footprint
  # update_frequency: 5.0
  # static_map: true
  # rolling_window: false

  global_frame: map

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: true
  # rolling_window: true
  neutral_cost: 50
  cost_factor: 0.8