local_costmap:
  # global_frame: odom
  # robot_base_frame: base_footprint
  # update_frequency: 5.0
  # publish_frequency: 2.0
  # static_map: false
  # rolling_window: true
  # width: 1.0
  # height: 1.0
  # resolution: 0.05

  global_frame: odom

  update_frequency: 10
  publish_frequency: 10
  transform_tolerance: 0.3 # 1.5x the sensor period  

  static_map: false  
  rolling_window: true
  width: 1
  height: 1
  resolution: 0.025

  laser_scan_sensor: {
    inf_is_valid: true
  }